#Aljabar Matrik
* penjelasan apa itu matrik
* operasi matrik
* penjumlahan, perkalian, pengurangan, transpose matrik
* buat program untuk mengalikan matrik a dan b

##Apa Itu Matrik?
Matriks adalah sebuah himpunan bilangan yang disusun dalam bentuk tabel berupa baris dan kolom. Secara lebih formal, matriks adalah suatu array atau struktur data dua dimensi yang terdiri dari elemen-elemen yang tersusun dalam baris dan kolom. Setiap elemen di dalam matriks dapat diidentifikasi dengan menggunakan dua indeks, yaitu indeks baris dan indeks kolom.

Matriks memiliki berbagai aplikasi dalam berbagai bidang, termasuk matematika, ilmu komputer, ekonomi, fisika, dan lain-lain. Beberapa aplikasi umum dari matriks termasuk representasi data dalam bentuk tabel, pemecahan sistem persamaan linear, transformasi geometri, analisis data, dan pemrograman komputer. Matriks juga menjadi dasar untuk berbagai konsep dan algoritma dalam bidang-bidang seperti aljabar linear, analisis numerik, dan pengolahan sinyal.

##Operasi Matrik

In [2]:
import numpy as np
import sympy as sy

In [9]:
a = np.array([[2, 4, 5],[1, 8, 7],[3, 0, 6]])
b = np.array([[-3, 4, 8],[2, -4, 6],[5, 7, 0]])
c = np.array([[4, 5],[-7, 9],[2, 8]])
d = np.array([[-5, 4, 8],[9, -4, 0],[5, 7, 0]])

In [8]:
#Penjumlahan Matrik
e = a + b
print(e)

[[-1  8 13]
 [ 3  4 13]
 [ 8  7  6]]


In [11]:
#Pengurangan Matrik
f = b - a
print(f)

[[ -5   0   3]
 [  1 -12  -1]
 [  2   7  -6]]


In [12]:
#Perkalian Matrik dengan Angka
g = 2 * a
print(g)

[[ 4  8 10]
 [ 2 16 14]
 [ 6  0 12]]


In [17]:
#Perkalian Matrik dengan Matrik
h = a @ c
i = a @ b
print(h, '\n', i)

[[-10  86]
 [-38 133]
 [ 24  63]] 
 [[27 27 40]
 [48 21 56]
 [21 54 24]]


In [5]:
#Transpose Matrik
ct = c.transpose()
cova = ct@c
cova

array([[ 69, -27],
       [-27, 170]])

##Program Perkalian Matrik A dan B

In [18]:
def perkalian_matriks(matrix1, matrix2):
    # Inisialisasi matriks hasil
    result = [[0 for i in range(len(matrix2[0]))] for i in range(len(matrix1))]

    # Perulangan untuk menghitung hasil perkalian matriks
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

matrix1 = a
matrix2 = b

# Panggil fungsi untuk perkalian matriks
hasil = perkalian_matriks(matrix1, matrix2)

# Cetak hasil perkalian matriks
if hasil:
    print("Hasil perkalian matriks:")
    for z in hasil:
        print(z)

Hasil perkalian matriks:
[27, 27, 40]
[48, 21, 56]
[21, 54, 24]
