#Aljabar Matriks
* penjelasan apa itu matriks
* operasi matriks
* penjumlahan, perkalian, pengurangan, transpose matriks
* buat program untuk mengalikan matriks a dan b

##Apa Itu Matriks?
Matriks adalah sebuah himpunan bilangan yang disusun dalam bentuk tabel berupa baris dan kolom. Setiap elemen di dalam matriks dapat diidentifikasi dengan menggunakan dua indeks, yaitu indeks baris dan indeks kolom.

berikut adalah contoh matriks :
$$A=\begin{bmatrix}2&4\\9&7\end{bmatrix}$$

##Operasi Matriks
Operasi matriks adalah operasi suatu bentuk matriks, seperti penjumlahan, pengurangan, perkalian, transpose, dan invers. untuk penjelasan lebih lanjutnya dengan beberapa contoh matriks seperti dibawah :

In [2]:
import numpy as np
import sympy as sy
a = np.array([[2, 4, 5],[1, 8, 7],[3, 0, 6]])
b = np.array([[-3, 4, 8],[2, -4, 6],[5, 7, 0]])
c = np.array([[4, 5],[-7, 9],[2, 8]])
d = np.array([[-5, 4, 8],[9, -4, 0],[5, 7, 0]])
inv = np.array([[4, 2, 3],[2, 3, 1],[0, 1, 1]])
inv2 = np.array([[0.2, 0.1, -0.7],[-0.2, 0.4, 0.2],[0.2, -0.4, 0.8]])

### Penjumlahan matriks
Penjumlahan matriks adalah operasi penjumlahan dari dua buah matriks untuk menghasilkan matriks baru. operasi penjumlahan matriks ini hanya dapat dilakukan ketika kedua matriks yang akan dijumlahkan memiliki elemen baris dan kolom yang sama. misalkan, matriks (3x3) hanya dapat dijumlahkan dengan matriks (3x3).
untuk rumusnya, seperti di bawah ini:

jika ada matriks
$$\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}$$ dijumlahkan dengan matriks
$$\begin{equation*}
B=
\begin{bmatrix}
p&q\\
r&s
\end{bmatrix}
\end{equation*}$$
maka penjumlahannya adalah $$\begin{equation*}
C=
\begin{bmatrix}
a+p&b+q\\
c+r&d+s
\end{bmatrix}
\end{equation*}$$

untuk contohnya dapat dilihat dibawah ini :

In [ ]:
#Penjumlahan Matrik
e = a + b
print(e)

[[-1  8 13]
 [ 3  4 13]
 [ 8  7  6]]


### Pengurangan Matriks
Untuk operasi pengurangan matriks, kurang lebih sama dengan operasi penjumlahan matriks. Operasi ini hanya dapat dilakukan pada dua matriks yang memiliki elemen baris dan kolom yang sama

In [ ]:
#Pengurangan Matrik
f = b - a
print(f)

[[ -5   0   3]
 [  1 -12  -1]
 [  2   7  -6]]


##Perkalian Matriks
Operasi perkalian matriks memilik 2 macam, yaitu :
* Perkalian matriks dengan bilangan real(skalar) dan,
* Perkalian matriks dengan matriks

###Perkalian Matriks dengan Bilangan Real(Skalar)
Operasi perkalian matriks dengan skalar dilakukan dengan cara mengalikan semua elemen matriks dengan skalar. contohnya :

$$\begin{equation*}A=2\times\begin{bmatrix}a&b\\c&d\end{bmatrix}\end{equation*}$$
maka operasinya adalah
$$\begin{equation*}A=\begin{bmatrix}a\times2&b\times2\\c\times2&d\times2\end{bmatrix}\end{equation*}$$



In [ ]:
#Perkalian Matrik dengan Bilangan Real(skalar)
g = 2 * a
print(g)

[[ 4  8 10]
 [ 2 16 14]
 [ 6  0 12]]


###Perkalian Matriks dengan Matriks
Operasi perkalian matriks dengan matriks dapat dilakukan dengan mengalikan elemen-elemen matriks dalam baris matriks pertama dengan elemen-elemen matriks dalam kolom matriks kedua. contohnya :
$$\begin{equation*}A=\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix}\end{equation*}$$ dikalikan dengan matriks $$\begin{equation*}B=\begin{bmatrix}p&q\\r&s\\t&u\end{bmatrix}\end{equation*}$$
maka operasinya adalah :
$$\begin{equation*}C=\begin{bmatrix}(a\times p+b\times r+c\times t)&(a\times q+b\times s+c\times u)\\(d\times p+e\times r+f\times t)&(d\times q+e\times s+f\times u)\end{bmatrix}\end{equation*}$$

In [ ]:
#Perkalian Matriks dengan Matriks
h = a @ c
i = a @ b
print(h, '\n', i)

[[-10  86]
 [-38 133]
 [ 24  63]] 
 [[27 27 40]
 [48 21 56]
 [21 54 24]]


##Transpose Matriks
Transpose matriks adalah operasi yang menukar posisi baris dan kolom matriks sehingga di peroleh matriks baru. contohnya :
$$\begin{equation*}A=\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix}\end{equation*}$$
maka transpose matriksnya adalah
$$\begin{equation*}A^T=\begin{bmatrix}a&d\\b&e\\c&f\end{bmatrix}\end{equation*}$$

In [ ]:
#Transpose Matrik
ct = c.transpose()
print(c)
print('\n')
print(ct)

[[ 4  5]
 [-7  9]
 [ 2  8]]


[[ 4 -7  2]
 [ 5  9  8]]


##Invers Matriks
Invers dapat diartikan sebagai sebuah kebalikan. yang berarti invers matriks adalah kebalikan dari suatu matriks. Misalnya, terdapat suatu fungsi $$f(x)=2x$$ maka invers dari fungsi tersebut adalah $$f^{-1}(x)= \frac{1}{2}x$$ Namun, tentu saja invers dari fungsi dan invers dari matriks itu berbeda, karena elemen baris dan kolom pada matriks memengaruhi cara mencari invers pada matriks tersebut. untuk rumusnya, seperti yang dibawah ini :
$$\begin{bmatrix}a&b\\c&d\end{bmatrix}^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}$$

In [ ]:
invers = np.linalg.inv(a)
print(invers)

[[ 1.33333333 -0.66666667 -0.33333333]
 [ 0.41666667 -0.08333333 -0.25      ]
 [-0.66666667  0.33333333  0.33333333]]


##Program Perkalian Matrik A dan B

In [ ]:
def perkalian_matriks(matrix1, matrix2):
    result = [[0 for i in range(len(matrix2[0]))] for i in range(len(matrix1))]

    # Perulangan untuk menghitung hasil perkalian matriks
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

matrix1 = a
matrix2 = b

# Panggil fungsi untuk perkalian matriks
hasil = perkalian_matriks(matrix1, matrix2)

# Cetak hasil perkalian matriks
if hasil:
    print("Hasil perkalian matriks:")
    for z in hasil:
        print(z)

Hasil perkalian matriks:
[27, 27, 40]
[48, 21, 56]
[21, 54, 24]
